# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
# Replace 'postgres' below with your <correct_password> if different
spring.datasource.password=0531
spring.datasource.driver-class-name=org.postgresql.Driver

# Execute schema.sql to initialize the database tables
spring.sql.init.mode=always
# Continue if tables already exist or if minor errors occur
spring.sql.init.continue-on-error=true
